This notebook provides an example code for using the IGA2D class

In [1]:
from IGA import IGA2D
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#Assign knot vectors, control points, and weights
knot_vector1 = [0, 0, 1, 2, 3, 3]
knot_vector2 = [0, 0, 1, 2, 2]
control_points = np.array([[[0,0],[1,0],[2,0],[3,0]],[[0,1],[1,1],[2,1],[3,1]],[[0,2],[1,2],[2,2],[3,2]]], dtype=np.double)
weights = np.ones_like(control_points[:,:,0])

#Instantiate the problem
iga = IGA2D(knot_vector1, 1, knot_vector2, 1, control_points, weights)

#Assemble stiffness matrix
iga.assemble()

#Create a boundary condition node set and values for the top side
ns1 = np.array([8, 9, 10, 11], dtype=np.int64)
val1 = np.cos(np.pi * np.array([0., 1., 2., 3.]) / 6.) * 100

#Create a boundary condition node set for the right side
ns2 = np.array([3, 7, 11], dtype=np.int64)
val2 = np.zeros(len(ns2))

#Apply boundary conditions
iga.apply_bcs(ns1,val1)
iga.apply_bcs(ns2,val2)

#Solve
iga.solve()

#Show solution
iga.get_solution()

[[[ 0.66666667 -0.16666667 -0.16666667 -0.33333333]
  [-0.16666667  0.66666667 -0.33333333 -0.16666667]
  [-0.16666667 -0.33333333  0.66666667 -0.16666667]
  [-0.33333333 -0.16666667 -0.16666667  0.66666667]]

 [[ 0.66666667 -0.16666667 -0.16666667 -0.33333333]
  [-0.16666667  0.66666667 -0.33333333 -0.16666667]
  [-0.16666667 -0.33333333  0.66666667 -0.16666667]
  [-0.33333333 -0.16666667 -0.16666667  0.66666667]]

 [[ 0.66666667 -0.16666667 -0.16666667 -0.33333333]
  [-0.16666667  0.66666667 -0.33333333 -0.16666667]
  [-0.16666667 -0.33333333  0.66666667 -0.16666667]
  [-0.33333333 -0.16666667 -0.16666667  0.66666667]]

 [[ 0.66666667 -0.16666667 -0.16666667 -0.33333333]
  [-0.16666667  0.66666667 -0.33333333 -0.16666667]
  [-0.16666667 -0.33333333  0.66666667 -0.16666667]
  [-0.33333333 -0.16666667 -0.16666667  0.66666667]]

 [[ 0.66666667 -0.16666667 -0.16666667 -0.33333333]
  [-0.16666667  0.66666667 -0.33333333 -0.16666667]
  [-0.16666667 -0.33333333  0.66666667 -0.16666667]
  [-

ValueError: array is not broadcastable to correct shape

In [ ]:
#Plot
iga.plot_solution()

We can compare this result to the finite element example result [here](http://nbviewer.ipython.org/github/johnfoster-pge-utexas/PGE383-AdvGeomechanics/blob/master/files/assignment5_solution.ipynb)

In [ ]:
iga.connectivity_array

In [ ]:
indices = iga.connectivity_array[:,None]# + K.shape[1]*idx).ravel('f')

In [5]:
indices = (iga.connectivity_array[:,None] + iga.K.shape[1] * iga.connectivity_array).ravel('f')
#np.add.at(iga.K.ravel(), indices, iga.ke.ravel())

In [8]:
iga.connectivity_array[:,None]# + iga.K.shape[1] * iga.connectivity_array)

array([[[ 5,  4,  1,  0]],

       [[ 6,  5,  2,  1]],

       [[ 7,  6,  3,  2]],

       [[ 9,  8,  5,  4]],

       [[10,  9,  6,  5]],

       [[11, 10,  7,  6]]])

In [11]:
iga.connectivity_array[:,None] + iga.K.shape[1] * iga.connectivity_array

array([[[ 65,  52,  13,   0],
        [ 77,  64,  25,  12],
        [ 89,  76,  37,  24],
        [113, 100,  61,  48],
        [125, 112,  73,  60],
        [137, 124,  85,  72]],

       [[ 66,  53,  14,   1],
        [ 78,  65,  26,  13],
        [ 90,  77,  38,  25],
        [114, 101,  62,  49],
        [126, 113,  74,  61],
        [138, 125,  86,  73]],

       [[ 67,  54,  15,   2],
        [ 79,  66,  27,  14],
        [ 91,  78,  39,  26],
        [115, 102,  63,  50],
        [127, 114,  75,  62],
        [139, 126,  87,  74]],

       [[ 69,  56,  17,   4],
        [ 81,  68,  29,  16],
        [ 93,  80,  41,  28],
        [117, 104,  65,  52],
        [129, 116,  77,  64],
        [141, 128,  89,  76]],

       [[ 70,  57,  18,   5],
        [ 82,  69,  30,  17],
        [ 94,  81,  42,  29],
        [118, 105,  66,  53],
        [130, 117,  78,  65],
        [142, 129,  90,  77]],

       [[ 71,  58,  19,   6],
        [ 83,  70,  31,  18],
        [ 95,  82,  43,  30],
